//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiViewer.App.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GiViewer.App.Resources.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Abort 的本地化字符串。
        /// </summary>
        public static string Dialog_Button_Abort {
            get {
                return ResourceManager.GetString("Dialog.Button.Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Dialog_Button_Cancel {
            get {
                return ResourceManager.GetString("Dialog.Button.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Continue 的本地化字符串。
        /// </summary>
        public static string Dialog_Button_Continue {
            get {
                return ResourceManager.GetString("Dialog.Button.Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discard 的本地化字符串。
        /// </summary>
        public static string Dialog_Button_Discard {
            get {
                return ResourceManager.GetString("Dialog.Button.Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore 的本地化字符串。
        /// </summary>
        public static string Dialog_Button_Ignore {
            get {
                return ResourceManager.GetString("Dialog.Button.Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string Dialog_Button_No {
            get {
                return ResourceManager.GetString("Dialog.Button.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ok 的本地化字符串。
        /// </summary>
        public static string Dialog_Button_Ok {
            get {
                return ResourceManager.GetString("Dialog.Button.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retry 的本地化字符串。
        /// </summary>
        public static string Dialog_Button_Retry {
            get {
                return ResourceManager.GetString("Dialog.Button.Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Dialog_Button_Save {
            get {
                return ResourceManager.GetString("Dialog.Button.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try Again 的本地化字符串。
        /// </summary>
        public static string Dialog_Button_Try {
            get {
                return ResourceManager.GetString("Dialog.Button.Try", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string Dialog_Button_Yes {
            get {
                return ResourceManager.GetString("Dialog.Button.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing Title 的本地化字符串。
        /// </summary>
        public static string Dialog_Title_Missing {
            get {
                return ResourceManager.GetString("Dialog.Title.Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string Menu_File_Exit {
            get {
                return ResourceManager.GetString("Menu.File.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string Menu_File_New {
            get {
                return ResourceManager.GetString("Menu.File.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string Menu_File_Open {
            get {
                return ResourceManager.GetString("Menu.File.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Menu_File_Save {
            get {
                return ResourceManager.GetString("Menu.File.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save As 的本地化字符串。
        /// </summary>
        public static string Menu_File_SaveAs {
            get {
                return ResourceManager.GetString("Menu.File.SaveAs", resourceCulture);
            }
        }
    }
}
